//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NexGenFlow.NexGen
{

    public partial class document : XPLiteObject
    {
        long fid;
        [Key]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        int fpackageid;
        public int packageid
        {
            get { return fpackageid; }
            set { SetPropertyValue<int>("packageid", ref fpackageid, value); }
        }
        string fdoc_name;
        [Size(255)]
        public string doc_name
        {
            get { return fdoc_name; }
            set { SetPropertyValue<string>("doc_name", ref fdoc_name, value); }
        }
        string fdoc_path;
        [Size(512)]
        public string doc_path
        {
            get { return fdoc_path; }
            set { SetPropertyValue<string>("doc_path", ref fdoc_path, value); }
        }
        string fdescription;
        [Size(512)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        int fstatusid;
        public int statusid
        {
            get { return fstatusid; }
            set { SetPropertyValue<int>("statusid", ref fstatusid, value); }
        }
        string fusername;
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        DateTime fcreated_date;
        public DateTime created_date
        {
            get { return fcreated_date; }
            set { SetPropertyValue<DateTime>("created_date", ref fcreated_date, value); }
        }
        DateTime fmodified_date;
        public DateTime modified_date
        {
            get { return fmodified_date; }
            set { SetPropertyValue<DateTime>("modified_date", ref fmodified_date, value); }
        }
        string fdoctype;
        [Indexed(Name = @"Index1")]
        [Size(255)]
        public string doctype
        {
            get { return fdoctype; }
            set { SetPropertyValue<string>("doctype", ref fdoctype, value); }
        }
        double ftotal;
        public double total
        {
            get { return ftotal; }
            set { SetPropertyValue<double>("total", ref ftotal, value); }
        }
        string ftransaction_date;
        [Size(20)]
        public string transaction_date
        {
            get { return ftransaction_date; }
            set { SetPropertyValue<string>("transaction_date", ref ftransaction_date, value); }
        }
        string freceipt_id;
        [Size(20)]
        public string receipt_id
        {
            get { return freceipt_id; }
            set { SetPropertyValue<string>("receipt_id", ref freceipt_id, value); }
        }
        string ftransaction_time;
        [Size(20)]
        public string transaction_time
        {
            get { return ftransaction_time; }
            set { SetPropertyValue<string>("transaction_time", ref ftransaction_time, value); }
        }
        string fimage_2;
        public string image_2
        {
            get { return fimage_2; }
            set { SetPropertyValue<string>("image_2", ref fimage_2, value); }
        }
        string fimage_3;
        public string image_3
        {
            get { return fimage_3; }
            set { SetPropertyValue<string>("image_3", ref fimage_3, value); }
        }
        string fimage_4;
        public string image_4
        {
            get { return fimage_4; }
            set { SetPropertyValue<string>("image_4", ref fimage_4, value); }
        }
        string fimage_5;
        public string image_5
        {
            get { return fimage_5; }
            set { SetPropertyValue<string>("image_5", ref fimage_5, value); }
        }
        string fimage_6;
        public string image_6
        {
            get { return fimage_6; }
            set { SetPropertyValue<string>("image_6", ref fimage_6, value); }
        }
        string fimage_7;
        public string image_7
        {
            get { return fimage_7; }
            set { SetPropertyValue<string>("image_7", ref fimage_7, value); }
        }
        string fimage_8;
        public string image_8
        {
            get { return fimage_8; }
            set { SetPropertyValue<string>("image_8", ref fimage_8, value); }
        }
        string fimage_9;
        public string image_9
        {
            get { return fimage_9; }
            set { SetPropertyValue<string>("image_9", ref fimage_9, value); }
        }
        string fbanner_id;
        public string banner_id
        {
            get { return fbanner_id; }
            set { SetPropertyValue<string>("banner_id", ref fbanner_id, value); }
        }
    }

}
