//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NexGenFlow.NexGen
{

    public partial class package_assignment : XPLiteObject
    {
        long fid;
        [Key]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        int fpackageid;
        public int packageid
        {
            get { return fpackageid; }
            set { SetPropertyValue<int>("packageid", ref fpackageid, value); }
        }
        string fusername;
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        DateTime fcreated_date;
        public DateTime created_date
        {
            get { return fcreated_date; }
            set { SetPropertyValue<DateTime>("created_date", ref fcreated_date, value); }
        }
        bool fis_enabled;
        public bool is_enabled
        {
            get { return fis_enabled; }
            set { SetPropertyValue<bool>("is_enabled", ref fis_enabled, value); }
        }
        int fpriority;
        public int priority
        {
            get { return fpriority; }
            set { SetPropertyValue<int>("priority", ref fpriority, value); }
        }
    }

}
